select * from ns_posts where post_title = 'Говядина тушеная 1-ый сорт' and post_type='product'
select * from ns_posts where post_title = 'Говядина тушеная 1-ый сорт' and post_type='product'
select * from ns_posts where post_title = 'Говядина тушеная в/сорт' and post_type='product'
select * from ns_posts where post_title = 'Говядина тушеная в/сорт' and post_type='product'
select * from ns_posts where post_title = 'Говядина тушеная в/сорт' and post_type='product'
select * from ns_posts where post_title = 'Свинина тушеная в/сорт' and post_type='product'
select * from ns_posts where post_title = 'Каша гречневая с говядиной по-деревенски' and post_type='product'
select * from ns_posts where post_title = 'Каша перловая с говядиной по-деревенски' and post_type='product'
select * from ns_posts where post_title = 'Каша рисовая с говядиной по-домашнему' and post_type='product'
select * from ns_posts where post_title = 'Каша перловая с говядиной' and post_type='product'
select * from ns_posts where post_title = 'Каша гречневая с говядиной' and post_type='product'
select * from ns_posts where post_title = 'Каша рисовая с говядиной' and post_type='product'
select * from ns_posts where post_title = 'Мясо цыплят в собственном соку' and post_type='product'
select * from ns_posts where post_title = 'Герцог' and post_type='product'
select * from ns_posts where post_title = 'Герцог' and post_type='product'
select * from ns_posts where post_title = 'Лорд' and post_type='product'
select * from ns_posts where post_title = 'Лорд' and post_type='product'
select * from ns_posts where post_title = 'Полкан' and post_type='product'
select * from ns_posts where post_title = 'Полкан' and post_type='product'
select * from ns_posts where post_title = 'Мясо птицы + печень' and post_type='product'
select * from ns_posts where post_title = 'Говядина + рубец' and post_type='product'
select * from ns_posts where post_title = 'Субпродукты + баранина для собак' and post_type='product'
select * from ns_posts where post_title = 'Субпродукты + баранина для кошек' and post_type='product'
select * from ns_posts where post_title = 'Аппетитные. Стандарт' and post_type='product'
select * from ns_posts where post_title = 'Барсик Гурман' and post_type='product'
select * from ns_posts where post_title = 'Лайка Гурман' and post_type='product'
select * from ns_posts where post_title = 'Лакомые. Стандарт' and post_type='product'
select * from ns_posts where post_title = 'Паштет для взрослых кошек с печенью' and post_type='product'
select * from ns_posts where post_title = 'Паштет для взрослых кошек с курицей' and post_type='product'
select * from ns_posts where post_title = 'Колбаса №1 в/сорт из м/инд.' and post_type='product'
select * from ns_posts where post_title = 'По спецзаказу в/сорт из м/инд.' and post_type='product'
select * from ns_posts where post_title = '"Сардельки ""На все 100"" в/сорт из м/инд. (газ.уп.)"' and post_type='product'
select * from ns_posts where post_title = 'Сосиски №1 из м/инд. в/сорт (газ.уп.)' and post_type='product'
select * from ns_posts where post_title = '"Филе ""Панское"" с/в из м/инд. (газ.уп.)"' and post_type='product'
select * from ns_posts where post_title = 'Салями Говяжья с/к 1-ый сорт в обсыпке' and post_type='product'
select * from ns_posts where post_title = 'Салями Говяжья с/к 1-ый сорт (вак.уп.)' and post_type='product'
select * from ns_posts where post_title = 'Салями Еврейская деликатесная с/к 1-ый сорт (вак.уп.)' and post_type='product'
select * from ns_posts where post_title = 'Салями Еврейская деликатесная с/к 1-ый сорт в обсыпке' and post_type='product'
select * from ns_posts where post_title = 'Говядина' and post_type='product'
select * from ns_posts where post_title = 'Говядина + индейка' and post_type='product'
select * from ns_posts where post_title = 'Говядина + кролик' and post_type='product'
select * from ns_posts where post_title = 'Говядина + печень' and post_type='product'
select * from ns_posts where post_title = 'Говядина + сердце' and post_type='product'
select * from ns_posts where post_title = 'Говядина + язык' and post_type='product'
select * from ns_posts where post_title = 'Говядина нежная' and post_type='product'
select * from ns_posts where post_title = 'Говядина с гречневой крупой' and post_type='product'
select * from ns_posts where post_title = 'Говядина сочная' and post_type='product'
select * from ns_posts where post_title = 'Говядина элитная' and post_type='product'
select * from ns_posts where post_title = 'Индейка + овощи' and post_type='product'
select * from ns_posts where post_title = 'Мясо цыплят с картофелем и морковью' and post_type='product'
select * from ns_posts where post_title = 'Пюре из кролика' and post_type='product'
select * from ns_posts where post_title = 'Пюре из мяса индейки' and post_type='product'
select * from ns_posts where post_title = 'Пюре из мяса цыплят' and post_type='product'
select * from ns_posts where post_title = 'Пюре из яблок и черники' and post_type='product'
select * from ns_posts where post_title = 'Пюре яблочное' and post_type='product'
select * from ns_posts where post_title = 'Пюре из груш' and post_type='product'
select * from ns_posts where post_title = 'Пюре из персиков' and post_type='product'
select * from ns_posts where post_title = 'Пюре из яблок и чернослива' and post_type='product'
select * from ns_posts where post_title = 'Пюре из кабачков' and post_type='product'
select * from ns_posts where post_title = 'Пюре морковное' and post_type='product'
select * from ns_posts where post_title = 'Пюре тыквенное' and post_type='product'
select * from ns_posts where post_title = 'Пюре из брокколи' and post_type='product'
select * from ns_posts where post_title = 'Пюре из цветной капусты' and post_type='product'
select * from ns_posts where post_title = 'Говядина сочная' and post_type='product'
select * from ns_posts where post_title = 'Говядина с мясом цыплят' and post_type='product'
select * from ns_posts where post_title = 'Говядина плюс индейка' and post_type='product'
select * from ns_posts where post_title = 'Пюре из мяса цыплят' and post_type='product'
select * from ns_posts where post_title = 'Пюре из мяса индейки ' and post_type='product'
select * from ns_posts where post_title = 'Мясо индейки с печенью' and post_type='product'
select * from ns_posts where post_title = 'Мясо индейки с языком' and post_type='product'
select * from ns_posts where post_title = 'Пюре из яблок с кобыльим молоком' and post_type='product'
select * from ns_posts where post_title = 'Пюре из яблок и черники с козьим йогуртом и злаками ' and post_type='product'
select * from ns_posts where post_title = 'Пюре из банана и клубники с козьим йогуртом ' and post_type='product'
select * from ns_posts where post_title = 'Пюре из груш с кобыльим молоком ' and post_type='product'
select * from ns_posts where post_title = 'Пюре из яблок и банана с козьим йогуртом ' and post_type='product'
select * from ns_posts where post_title = 'Пюре из яблока и чернослива с козьим йогуртом ' and post_type='product'
